//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace Videos.VideosReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.sapo.pt/definitions", ConfigurationName="VideosReference.VideosSoapSecure")]
    public interface VideosSoapSecure {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/AddVideo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Video> AddVideoAsync(Videos.VideosReference.VideoSubmition Video, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/AddVideoPost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Video> AddVideoPostAsync(Videos.VideosReference.VideoSubmition Video, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/AddVideoToPlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task AddVideoToPlaylistAsync(string Randname, string Playlist, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/CheckPlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Playlist> CheckPlaylistAsync(int PlaylistId, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/CheckVideo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Video> CheckVideoAsync(string VideoId, string Email, string VideoRandname, string Interface, int ShowComments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/CreatePlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Playlist> CreatePlaylistAsync(string Email, Videos.VideosReference.PlaylistSubmition Playlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/CreateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task CreateUserAsync(string Email, string Username, int NewsLetter, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/DeletePlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task DeletePlaylistAsync(int PlaylistId, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/DeleteVideo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task DeleteVideoAsync(string Randname, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/EditPlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task EditPlaylistAsync(Videos.VideosReference.PlaylistSubmition Playlist, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/EditVideo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task EditVideoAsync(Videos.VideosReference.VideoSubmition Video, string Email, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/GetEncodeParameters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.Params> GetEncodeParametersAsync(int EncId, int IdVideoWidth, int IdVideoHeight, int IdAudioBitrate, int IdAudioNch, float IdVideoFps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/GetEncodeProfilesForUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.GetEncodeProfilesForUserResponse> GetEncodeProfilesForUserAsync(Videos.VideosReference.GetEncodeProfilesForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.User> GetUserInfoAsync(string Email, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/GetUserInfoForDashboard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.UserForDashboad> GetUserInfoForDashboardAsync(string Email, string Username, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/ListCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListCategoriesResponse> ListCategoriesAsync(Videos.VideosReference.ListCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/ListUserPlaylists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserPlaylistsResponse> ListUserPlaylistsAsync(Videos.VideosReference.ListUserPlaylistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/ListUserTags", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserTagsResponse> ListUserTagsAsync(Videos.VideosReference.ListUserTagsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/ListUserVideos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserVideosResponse> ListUserVideosAsync(Videos.VideosReference.ListUserVideosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/ListVideosFromPlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListVideosFromPlaylistResponse> ListVideosFromPlaylistAsync(Videos.VideosReference.ListVideosFromPlaylistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/NotifyComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task NotifyCommentAsync(string Randname, string Interface);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Videos.VideosReference.QueryResponse> QueryAsync(Videos.VideosReference.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.sapo.pt/definitions/RemoveVideoFromPlaylist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task RemoveVideoFromPlaylistAsync(string Randname, string Playlist, string Email, string Interface);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class VideoSubmition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subtitleField;
        
        private string synopseField;
        
        private string titleField;
        
        private int activeField;
        
        private string fileNameField;
        
        private string randnameField;
        
        private string tagsField;
        
        private string referedExternalField;
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private int hdField;
        
        private bool hdFieldSpecified;
        
        private int canPublishField;
        
        private bool canPublishFieldSpecified;
        
        private int canShareField;
        
        private bool canShareFieldSpecified;
        
        private string publishDateField;
        
        private string removalDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
                this.RaisePropertyChanged("Subtitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Synopse {
            get {
                return this.synopseField;
            }
            set {
                this.synopseField = value;
                this.RaisePropertyChanged("Synopse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Randname {
            get {
                return this.randnameField;
            }
            set {
                this.randnameField = value;
                this.RaisePropertyChanged("Randname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReferedExternal {
            get {
                return this.referedExternalField;
            }
            set {
                this.referedExternalField = value;
                this.RaisePropertyChanged("ReferedExternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified {
            get {
                return this.categoryIdFieldSpecified;
            }
            set {
                this.categoryIdFieldSpecified = value;
                this.RaisePropertyChanged("CategoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int HD {
            get {
                return this.hdField;
            }
            set {
                this.hdField = value;
                this.RaisePropertyChanged("HD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HDSpecified {
            get {
                return this.hdFieldSpecified;
            }
            set {
                this.hdFieldSpecified = value;
                this.RaisePropertyChanged("HDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int CanPublish {
            get {
                return this.canPublishField;
            }
            set {
                this.canPublishField = value;
                this.RaisePropertyChanged("CanPublish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanPublishSpecified {
            get {
                return this.canPublishFieldSpecified;
            }
            set {
                this.canPublishFieldSpecified = value;
                this.RaisePropertyChanged("CanPublishSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CanShare {
            get {
                return this.canShareField;
            }
            set {
                this.canShareField = value;
                this.RaisePropertyChanged("CanShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanShareSpecified {
            get {
                return this.canShareFieldSpecified;
            }
            set {
                this.canShareFieldSpecified = value;
                this.RaisePropertyChanged("CanShareSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PublishDate {
            get {
                return this.publishDateField;
            }
            set {
                this.publishDateField = value;
                this.RaisePropertyChanged("PublishDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RemovalDate {
            get {
                return this.removalDateField;
            }
            set {
                this.removalDateField = value;
                this.RaisePropertyChanged("RemovalDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Tag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tag1Field;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Tag", Order=0)]
        public string Tag1 {
            get {
                return this.tag1Field;
            }
            set {
                this.tag1Field = value;
                this.RaisePropertyChanged("Tag1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("CountSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class UserForDashboad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalPublicVideosField;
        
        private int totalPrivateVideosField;
        
        private int totalPublicPlaylistField;
        
        private int totalPrivatePlaylistField;
        
        private int totalCommentsField;
        
        private int totalFavoritesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalPublicVideos {
            get {
                return this.totalPublicVideosField;
            }
            set {
                this.totalPublicVideosField = value;
                this.RaisePropertyChanged("TotalPublicVideos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalPrivateVideos {
            get {
                return this.totalPrivateVideosField;
            }
            set {
                this.totalPrivateVideosField = value;
                this.RaisePropertyChanged("TotalPrivateVideos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TotalPublicPlaylist {
            get {
                return this.totalPublicPlaylistField;
            }
            set {
                this.totalPublicPlaylistField = value;
                this.RaisePropertyChanged("TotalPublicPlaylist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalPrivatePlaylist {
            get {
                return this.totalPrivatePlaylistField;
            }
            set {
                this.totalPrivatePlaylistField = value;
                this.RaisePropertyChanged("TotalPrivatePlaylist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalComments {
            get {
                return this.totalCommentsField;
            }
            set {
                this.totalCommentsField = value;
                this.RaisePropertyChanged("TotalComments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalFavorites {
            get {
                return this.totalFavoritesField;
            }
            set {
                this.totalFavoritesField = value;
                this.RaisePropertyChanged("TotalFavorites");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int activeField;
        
        private int bannedField;
        
        private int commentCaptchaField;
        
        private int commentModerateField;
        
        private int commentNotifyField;
        
        private string creationDateField;
        
        private string emailField;
        
        private string lastLoginField;
        
        private int partnerField;
        
        private string uploadMailField;
        
        private string usernameField;
        
        private int viewAllField;
        
        private string websiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Banned {
            get {
                return this.bannedField;
            }
            set {
                this.bannedField = value;
                this.RaisePropertyChanged("Banned");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CommentCaptcha {
            get {
                return this.commentCaptchaField;
            }
            set {
                this.commentCaptchaField = value;
                this.RaisePropertyChanged("CommentCaptcha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int CommentModerate {
            get {
                return this.commentModerateField;
            }
            set {
                this.commentModerateField = value;
                this.RaisePropertyChanged("CommentModerate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CommentNotify {
            get {
                return this.commentNotifyField;
            }
            set {
                this.commentNotifyField = value;
                this.RaisePropertyChanged("CommentNotify");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LastLogin {
            get {
                return this.lastLoginField;
            }
            set {
                this.lastLoginField = value;
                this.RaisePropertyChanged("LastLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
                this.RaisePropertyChanged("Partner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UploadMail {
            get {
                return this.uploadMailField;
            }
            set {
                this.uploadMailField = value;
                this.RaisePropertyChanged("UploadMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int ViewAll {
            get {
                return this.viewAllField;
            }
            set {
                this.viewAllField = value;
                this.RaisePropertyChanged("ViewAll");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class EncodeProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string extensionField;
        
        private int toEncodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("Extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ToEncode {
            get {
                return this.toEncodeField;
            }
            set {
                this.toEncodeField = value;
                this.RaisePropertyChanged("ToEncode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Params : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int expWidthField;
        
        private int expHeightField;
        
        private int scaleWidthField;
        
        private int scaleHeightField;
        
        private int soundRateField;
        
        private int soundModeField;
        
        private float videoFpsField;
        
        private string videoExtensionField;
        
        private int videoBitrateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ExpWidth {
            get {
                return this.expWidthField;
            }
            set {
                this.expWidthField = value;
                this.RaisePropertyChanged("ExpWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ExpHeight {
            get {
                return this.expHeightField;
            }
            set {
                this.expHeightField = value;
                this.RaisePropertyChanged("ExpHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ScaleWidth {
            get {
                return this.scaleWidthField;
            }
            set {
                this.scaleWidthField = value;
                this.RaisePropertyChanged("ScaleWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ScaleHeight {
            get {
                return this.scaleHeightField;
            }
            set {
                this.scaleHeightField = value;
                this.RaisePropertyChanged("ScaleHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SoundRate {
            get {
                return this.soundRateField;
            }
            set {
                this.soundRateField = value;
                this.RaisePropertyChanged("SoundRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SoundMode {
            get {
                return this.soundModeField;
            }
            set {
                this.soundModeField = value;
                this.RaisePropertyChanged("SoundMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float VideoFps {
            get {
                return this.videoFpsField;
            }
            set {
                this.videoFpsField = value;
                this.RaisePropertyChanged("VideoFps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string VideoExtension {
            get {
                return this.videoExtensionField;
            }
            set {
                this.videoExtensionField = value;
                this.RaisePropertyChanged("VideoExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int VideoBitrate {
            get {
                return this.videoBitrateField;
            }
            set {
                this.videoBitrateField = value;
                this.RaisePropertyChanged("VideoBitrate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class PlaylistSubmition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string titleField;
        
        private int activeField;
        
        private string descriptionField;
        
        private string tagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Playlist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int activeField;
        
        private string creationDateField;
        
        private string descriptionField;
        
        private string titleField;
        
        private string tagsField;
        
        private string uRLField;
        
        private string thumbnailField;
        
        private int totalVideosField;
        
        private int resultTotalPlaylistsField;
        
        private bool resultTotalPlaylistsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
                this.RaisePropertyChanged("Thumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int TotalVideos {
            get {
                return this.totalVideosField;
            }
            set {
                this.totalVideosField = value;
                this.RaisePropertyChanged("TotalVideos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ResultTotalPlaylists {
            get {
                return this.resultTotalPlaylistsField;
            }
            set {
                this.resultTotalPlaylistsField = value;
                this.RaisePropertyChanged("ResultTotalPlaylists");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultTotalPlaylistsSpecified {
            get {
                return this.resultTotalPlaylistsFieldSpecified;
            }
            set {
                this.resultTotalPlaylistsFieldSpecified = value;
                this.RaisePropertyChanged("ResultTotalPlaylistsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class ESBCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eSBUsernameField;
        
        private string eSBPasswordField;
        
        private string eSBTokenField;
        
        private string[] eSBRolesField;
        
        private string eSBTokenTimeToLiveField;
        
        private string eSBTokenExtraInfoField;
        
        private string eSBPrimaryIdField;
        
        private string eSBUserTypeField;
        
        private string eSBCredentialsStoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ESBUsername {
            get {
                return this.eSBUsernameField;
            }
            set {
                this.eSBUsernameField = value;
                this.RaisePropertyChanged("ESBUsername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ESBPassword {
            get {
                return this.eSBPasswordField;
            }
            set {
                this.eSBPasswordField = value;
                this.RaisePropertyChanged("ESBPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ESBToken {
            get {
                return this.eSBTokenField;
            }
            set {
                this.eSBTokenField = value;
                this.RaisePropertyChanged("ESBToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ESBRole", IsNullable=false)]
        public string[] ESBRoles {
            get {
                return this.eSBRolesField;
            }
            set {
                this.eSBRolesField = value;
                this.RaisePropertyChanged("ESBRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ESBTokenTimeToLive {
            get {
                return this.eSBTokenTimeToLiveField;
            }
            set {
                this.eSBTokenTimeToLiveField = value;
                this.RaisePropertyChanged("ESBTokenTimeToLive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ESBTokenExtraInfo {
            get {
                return this.eSBTokenExtraInfoField;
            }
            set {
                this.eSBTokenExtraInfoField = value;
                this.RaisePropertyChanged("ESBTokenExtraInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ESBPrimaryId {
            get {
                return this.eSBPrimaryIdField;
            }
            set {
                this.eSBPrimaryIdField = value;
                this.RaisePropertyChanged("ESBPrimaryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ESBUserType {
            get {
                return this.eSBUserTypeField;
            }
            set {
                this.eSBUserTypeField = value;
                this.RaisePropertyChanged("ESBUserType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ESBCredentialsStore {
            get {
                return this.eSBCredentialsStoreField;
            }
            set {
                this.eSBCredentialsStoreField = value;
                this.RaisePropertyChanged("ESBCredentialsStore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Comment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private string nicknameField;
        
        private string websiteField;
        
        private string bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("Nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.sapo.pt/definitions")]
    public partial class Video : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int activeField;
        
        private string creationDateField;
        
        private int lengthField;
        
        private int pendingField;
        
        private bool pendingFieldSpecified;
        
        private string randnameField;
        
        private string subtitleField;
        
        private string synopseField;
        
        private string titleField;
        
        private string usernameField;
        
        private string uRLField;
        
        private string thumbnailField;
        
        private string embedField;
        
        private string ratingField;
        
        private string viewsField;
        
        private string commentsField;
        
        private string referedExternalField;
        
        private string tagsField;
        
        private Comment[] commentsContentField;
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private int hdField;
        
        private bool hdFieldSpecified;
        
        private int canPublishField;
        
        private bool canPublishFieldSpecified;
        
        private int canShareField;
        
        private bool canShareFieldSpecified;
        
        private int resultTotalVideosField;
        
        private bool resultTotalVideosFieldSpecified;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Pending {
            get {
                return this.pendingField;
            }
            set {
                this.pendingField = value;
                this.RaisePropertyChanged("Pending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PendingSpecified {
            get {
                return this.pendingFieldSpecified;
            }
            set {
                this.pendingFieldSpecified = value;
                this.RaisePropertyChanged("PendingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Randname {
            get {
                return this.randnameField;
            }
            set {
                this.randnameField = value;
                this.RaisePropertyChanged("Randname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
                this.RaisePropertyChanged("Subtitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Synopse {
            get {
                return this.synopseField;
            }
            set {
                this.synopseField = value;
                this.RaisePropertyChanged("Synopse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Thumbnail {
            get {
                return this.thumbnailField;
            }
            set {
                this.thumbnailField = value;
                this.RaisePropertyChanged("Thumbnail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Embed {
            get {
                return this.embedField;
            }
            set {
                this.embedField = value;
                this.RaisePropertyChanged("Embed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("Rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Views {
            get {
                return this.viewsField;
            }
            set {
                this.viewsField = value;
                this.RaisePropertyChanged("Views");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ReferedExternal {
            get {
                return this.referedExternalField;
            }
            set {
                this.referedExternalField = value;
                this.RaisePropertyChanged("ReferedExternal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Comment[] CommentsContent {
            get {
                return this.commentsContentField;
            }
            set {
                this.commentsContentField = value;
                this.RaisePropertyChanged("CommentsContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified {
            get {
                return this.categoryIdFieldSpecified;
            }
            set {
                this.categoryIdFieldSpecified = value;
                this.RaisePropertyChanged("CategoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int HD {
            get {
                return this.hdField;
            }
            set {
                this.hdField = value;
                this.RaisePropertyChanged("HD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HDSpecified {
            get {
                return this.hdFieldSpecified;
            }
            set {
                this.hdFieldSpecified = value;
                this.RaisePropertyChanged("HDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int CanPublish {
            get {
                return this.canPublishField;
            }
            set {
                this.canPublishField = value;
                this.RaisePropertyChanged("CanPublish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanPublishSpecified {
            get {
                return this.canPublishFieldSpecified;
            }
            set {
                this.canPublishFieldSpecified = value;
                this.RaisePropertyChanged("CanPublishSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int CanShare {
            get {
                return this.canShareField;
            }
            set {
                this.canShareField = value;
                this.RaisePropertyChanged("CanShare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CanShareSpecified {
            get {
                return this.canShareFieldSpecified;
            }
            set {
                this.canShareFieldSpecified = value;
                this.RaisePropertyChanged("CanShareSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int ResultTotalVideos {
            get {
                return this.resultTotalVideosField;
            }
            set {
                this.resultTotalVideosField = value;
                this.RaisePropertyChanged("ResultTotalVideos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResultTotalVideosSpecified {
            get {
                return this.resultTotalVideosFieldSpecified;
            }
            set {
                this.resultTotalVideosFieldSpecified = value;
                this.RaisePropertyChanged("ResultTotalVideosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEncodeProfilesForUser", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class GetEncodeProfilesForUserRequest {
        
        public GetEncodeProfilesForUserRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEncodeProfilesForUserResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class GetEncodeProfilesForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.EncodeProfile[] GetEncodeProfilesForUserResult;
        
        public GetEncodeProfilesForUserResponse() {
        }
        
        public GetEncodeProfilesForUserResponse(Videos.VideosReference.EncodeProfile[] GetEncodeProfilesForUserResult) {
            this.GetEncodeProfilesForUserResult = GetEncodeProfilesForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListCategories", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListCategoriesRequest {
        
        public ListCategoriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListCategoriesResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Category[] ListCategoriesResult;
        
        public ListCategoriesResponse() {
        }
        
        public ListCategoriesResponse(Videos.VideosReference.Category[] ListCategoriesResult) {
            this.ListCategoriesResult = ListCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserPlaylists", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserPlaylistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=1)]
        public string Interface;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=2)]
        public int Page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=3)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=4)]
        public string Order;
        
        public ListUserPlaylistsRequest() {
        }
        
        public ListUserPlaylistsRequest(string Email, string Interface, int Page, int Limit, string Order) {
            this.Email = Email;
            this.Interface = Interface;
            this.Page = Page;
            this.Limit = Limit;
            this.Order = Order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserPlaylistsResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserPlaylistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Playlist[] ListUserPlaylistsResult;
        
        public ListUserPlaylistsResponse() {
        }
        
        public ListUserPlaylistsResponse(Videos.VideosReference.Playlist[] ListUserPlaylistsResult) {
            this.ListUserPlaylistsResult = ListUserPlaylistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserTags", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserTagsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=1)]
        public string Interface;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=2)]
        public int Limit;
        
        public ListUserTagsRequest() {
        }
        
        public ListUserTagsRequest(string Email, string Interface, int Limit) {
            this.Email = Email;
            this.Interface = Interface;
            this.Limit = Limit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserTagsResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserTagsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Tag[] ListUserTagsResult;
        
        public ListUserTagsResponse() {
        }
        
        public ListUserTagsResponse(Videos.VideosReference.Tag[] ListUserTagsResult) {
            this.ListUserTagsResult = ListUserTagsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserVideos", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserVideosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=1)]
        public string Interface;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=2)]
        public string Order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=3)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=4)]
        public int Page;
        
        public ListUserVideosRequest() {
        }
        
        public ListUserVideosRequest(string Email, string Interface, string Order, int Limit, int Page) {
            this.Email = Email;
            this.Interface = Interface;
            this.Order = Order;
            this.Limit = Limit;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListUserVideosResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListUserVideosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Video[] ListUserVideosResult;
        
        public ListUserVideosResponse() {
        }
        
        public ListUserVideosResponse(Videos.VideosReference.Video[] ListUserVideosResult) {
            this.ListUserVideosResult = ListUserVideosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListVideosFromPlaylist", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListVideosFromPlaylistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        public string Playlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=1)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Interface;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=3)]
        public string Order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=4)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=5)]
        public int Page;
        
        public ListVideosFromPlaylistRequest() {
        }
        
        public ListVideosFromPlaylistRequest(string Playlist, string Email, string Interface, string Order, int Limit, int Page) {
            this.Playlist = Playlist;
            this.Email = Email;
            this.Interface = Interface;
            this.Order = Order;
            this.Limit = Limit;
            this.Page = Page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListVideosFromPlaylistResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class ListVideosFromPlaylistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Video[] ListVideosFromPlaylistResult;
        
        public ListVideosFromPlaylistResponse() {
        }
        
        public ListVideosFromPlaylistResponse(Videos.VideosReference.Video[] ListVideosFromPlaylistResult) {
            this.ListVideosFromPlaylistResult = ListVideosFromPlaylistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Query", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        public string Emails;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=1)]
        public string Tags;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=2)]
        public int Cos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=3)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=4)]
        public string Order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=5)]
        public int ViewAll;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=6)]
        public string Interface;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=7)]
        public int ShowTags;
        
        public QueryRequest() {
        }
        
        public QueryRequest(string Emails, string Tags, int Cos, int Limit, string Order, int ViewAll, string Interface, int ShowTags) {
            this.Emails = Emails;
            this.Tags = Tags;
            this.Cos = Cos;
            this.Limit = Limit;
            this.Order = Order;
            this.ViewAll = ViewAll;
            this.Interface = Interface;
            this.ShowTags = ShowTags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryResponse", WrapperNamespace="http://services.sapo.pt/definitions", IsWrapped=true)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.sapo.pt/definitions", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item")]
        public Videos.VideosReference.Video[] QueryResult;
        
        public QueryResponse() {
        }
        
        public QueryResponse(Videos.VideosReference.Video[] QueryResult) {
            this.QueryResult = QueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VideosSoapSecureChannel : Videos.VideosReference.VideosSoapSecure, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideosSoapSecureClient : System.ServiceModel.ClientBase<Videos.VideosReference.VideosSoapSecure>, Videos.VideosReference.VideosSoapSecure {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VideosSoapSecureClient() : 
                base(VideosSoapSecureClient.GetDefaultBinding(), VideosSoapSecureClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.VideosSoapSecure.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideosSoapSecureClient(EndpointConfiguration endpointConfiguration) : 
                base(VideosSoapSecureClient.GetBindingForEndpoint(endpointConfiguration), VideosSoapSecureClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideosSoapSecureClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VideosSoapSecureClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideosSoapSecureClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VideosSoapSecureClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideosSoapSecureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Video> AddVideoAsync(Videos.VideosReference.VideoSubmition Video, string Email) {
            return base.Channel.AddVideoAsync(Video, Email);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Video> AddVideoPostAsync(Videos.VideosReference.VideoSubmition Video, string Email) {
            return base.Channel.AddVideoPostAsync(Video, Email);
        }
        
        public System.Threading.Tasks.Task AddVideoToPlaylistAsync(string Randname, string Playlist, string Email, string Interface) {
            return base.Channel.AddVideoToPlaylistAsync(Randname, Playlist, Email, Interface);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Playlist> CheckPlaylistAsync(int PlaylistId, string Email, string Interface) {
            return base.Channel.CheckPlaylistAsync(PlaylistId, Email, Interface);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Video> CheckVideoAsync(string VideoId, string Email, string VideoRandname, string Interface, int ShowComments) {
            return base.Channel.CheckVideoAsync(VideoId, Email, VideoRandname, Interface, ShowComments);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Playlist> CreatePlaylistAsync(string Email, Videos.VideosReference.PlaylistSubmition Playlist) {
            return base.Channel.CreatePlaylistAsync(Email, Playlist);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(string Email, string Username, int NewsLetter, string Interface) {
            return base.Channel.CreateUserAsync(Email, Username, NewsLetter, Interface);
        }
        
        public System.Threading.Tasks.Task DeletePlaylistAsync(int PlaylistId, string Email, string Interface) {
            return base.Channel.DeletePlaylistAsync(PlaylistId, Email, Interface);
        }
        
        public System.Threading.Tasks.Task DeleteVideoAsync(string Randname, string Email, string Interface) {
            return base.Channel.DeleteVideoAsync(Randname, Email, Interface);
        }
        
        public System.Threading.Tasks.Task EditPlaylistAsync(Videos.VideosReference.PlaylistSubmition Playlist, string Email, string Interface) {
            return base.Channel.EditPlaylistAsync(Playlist, Email, Interface);
        }
        
        public System.Threading.Tasks.Task EditVideoAsync(Videos.VideosReference.VideoSubmition Video, string Email, string Interface) {
            return base.Channel.EditVideoAsync(Video, Email, Interface);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.Params> GetEncodeParametersAsync(int EncId, int IdVideoWidth, int IdVideoHeight, int IdAudioBitrate, int IdAudioNch, float IdVideoFps) {
            return base.Channel.GetEncodeParametersAsync(EncId, IdVideoWidth, IdVideoHeight, IdAudioBitrate, IdAudioNch, IdVideoFps);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.GetEncodeProfilesForUserResponse> Videos.VideosReference.VideosSoapSecure.GetEncodeProfilesForUserAsync(Videos.VideosReference.GetEncodeProfilesForUserRequest request) {
            return base.Channel.GetEncodeProfilesForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.GetEncodeProfilesForUserResponse> GetEncodeProfilesForUserAsync() {
            Videos.VideosReference.GetEncodeProfilesForUserRequest inValue = new Videos.VideosReference.GetEncodeProfilesForUserRequest();
            return ((Videos.VideosReference.VideosSoapSecure)(this)).GetEncodeProfilesForUserAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.User> GetUserInfoAsync(string Email, string Username) {
            return base.Channel.GetUserInfoAsync(Email, Username);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.UserForDashboad> GetUserInfoForDashboardAsync(string Email, string Username, string Interface) {
            return base.Channel.GetUserInfoForDashboardAsync(Email, Username, Interface);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListCategoriesResponse> Videos.VideosReference.VideosSoapSecure.ListCategoriesAsync(Videos.VideosReference.ListCategoriesRequest request) {
            return base.Channel.ListCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.ListCategoriesResponse> ListCategoriesAsync() {
            Videos.VideosReference.ListCategoriesRequest inValue = new Videos.VideosReference.ListCategoriesRequest();
            return ((Videos.VideosReference.VideosSoapSecure)(this)).ListCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserPlaylistsResponse> Videos.VideosReference.VideosSoapSecure.ListUserPlaylistsAsync(Videos.VideosReference.ListUserPlaylistsRequest request) {
            return base.Channel.ListUserPlaylistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.ListUserPlaylistsResponse> ListUserPlaylistsAsync(string Email, string Interface, int Page, int Limit, string Order) {
            Videos.VideosReference.ListUserPlaylistsRequest inValue = new Videos.VideosReference.ListUserPlaylistsRequest();
            inValue.Email = Email;
            inValue.Interface = Interface;
            inValue.Page = Page;
            inValue.Limit = Limit;
            inValue.Order = Order;
            return ((Videos.VideosReference.VideosSoapSecure)(this)).ListUserPlaylistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserTagsResponse> Videos.VideosReference.VideosSoapSecure.ListUserTagsAsync(Videos.VideosReference.ListUserTagsRequest request) {
            return base.Channel.ListUserTagsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.ListUserTagsResponse> ListUserTagsAsync(string Email, string Interface, int Limit) {
            Videos.VideosReference.ListUserTagsRequest inValue = new Videos.VideosReference.ListUserTagsRequest();
            inValue.Email = Email;
            inValue.Interface = Interface;
            inValue.Limit = Limit;
            return ((Videos.VideosReference.VideosSoapSecure)(this)).ListUserTagsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListUserVideosResponse> Videos.VideosReference.VideosSoapSecure.ListUserVideosAsync(Videos.VideosReference.ListUserVideosRequest request) {
            return base.Channel.ListUserVideosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.ListUserVideosResponse> ListUserVideosAsync(string Email, string Interface, string Order, int Limit, int Page) {
            Videos.VideosReference.ListUserVideosRequest inValue = new Videos.VideosReference.ListUserVideosRequest();
            inValue.Email = Email;
            inValue.Interface = Interface;
            inValue.Order = Order;
            inValue.Limit = Limit;
            inValue.Page = Page;
            return ((Videos.VideosReference.VideosSoapSecure)(this)).ListUserVideosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.ListVideosFromPlaylistResponse> Videos.VideosReference.VideosSoapSecure.ListVideosFromPlaylistAsync(Videos.VideosReference.ListVideosFromPlaylistRequest request) {
            return base.Channel.ListVideosFromPlaylistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.ListVideosFromPlaylistResponse> ListVideosFromPlaylistAsync(string Playlist, string Email, string Interface, string Order, int Limit, int Page) {
            Videos.VideosReference.ListVideosFromPlaylistRequest inValue = new Videos.VideosReference.ListVideosFromPlaylistRequest();
            inValue.Playlist = Playlist;
            inValue.Email = Email;
            inValue.Interface = Interface;
            inValue.Order = Order;
            inValue.Limit = Limit;
            inValue.Page = Page;
            return ((Videos.VideosReference.VideosSoapSecure)(this)).ListVideosFromPlaylistAsync(inValue);
        }
        
        public System.Threading.Tasks.Task NotifyCommentAsync(string Randname, string Interface) {
            return base.Channel.NotifyCommentAsync(Randname, Interface);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Videos.VideosReference.QueryResponse> Videos.VideosReference.VideosSoapSecure.QueryAsync(Videos.VideosReference.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Videos.VideosReference.QueryResponse> QueryAsync(string Emails, string Tags, int Cos, int Limit, string Order, int ViewAll, string Interface, int ShowTags) {
            Videos.VideosReference.QueryRequest inValue = new Videos.VideosReference.QueryRequest();
            inValue.Emails = Emails;
            inValue.Tags = Tags;
            inValue.Cos = Cos;
            inValue.Limit = Limit;
            inValue.Order = Order;
            inValue.ViewAll = ViewAll;
            inValue.Interface = Interface;
            inValue.ShowTags = ShowTags;
            return ((Videos.VideosReference.VideosSoapSecure)(this)).QueryAsync(inValue);
        }
        
        public System.Threading.Tasks.Task RemoveVideoFromPlaylistAsync(string Randname, string Playlist, string Email, string Interface) {
            return base.Channel.RemoveVideoFromPlaylistAsync(Randname, Playlist, Email, Interface);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.VideosSoapSecure)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.VideosSoapSecure)) {
                return new System.ServiceModel.EndpointAddress("https://services.sapo.pt/Videos");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return VideosSoapSecureClient.GetBindingForEndpoint(EndpointConfiguration.VideosSoapSecure);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return VideosSoapSecureClient.GetEndpointAddress(EndpointConfiguration.VideosSoapSecure);
        }
        
        public enum EndpointConfiguration {
            
            VideosSoapSecure,
        }
    }
}
