\contentsline {lstlisting}{\numberline {3.1}HTTP GET using \lstinline [basicstyle=\relax \fontsize {10.95}{13.6}\selectfont \abovedisplayskip 11\p@ plus3\p@ minus6\p@ \abovedisplayshortskip \z@ plus3\p@ \belowdisplayshortskip 6.5\p@ plus3.5\p@ minus3\p@ \belowdisplayskip \abovedisplayskip \let \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \tt ,aboveskip=10pt,showstringspaces=false]|ESBUsername| and \lstinline [basicstyle=\relax \fontsize {10.95}{13.6}\selectfont \abovedisplayskip 11\p@ plus3\p@ minus6\p@ \abovedisplayshortskip \z@ plus3\p@ \belowdisplayshortskip 6.5\p@ plus3.5\p@ minus3\p@ \belowdisplayskip \abovedisplayskip \let \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \tt ,aboveskip=10pt,showstringspaces=false]|ESBPassword|}{5}{lstlisting.3.1}
\contentsline {lstlisting}{\numberline {3.2}HTTP GET using \lstinline [basicstyle=\relax \fontsize {10.95}{13.6}\selectfont \abovedisplayskip 11\p@ plus3\p@ minus6\p@ \abovedisplayshortskip \z@ plus3\p@ \belowdisplayshortskip 6.5\p@ plus3.5\p@ minus3\p@ \belowdisplayskip \abovedisplayskip \let \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \tt ,aboveskip=10pt,showstringspaces=false]|ESBToken|}{6}{lstlisting.3.2}
\contentsline {lstlisting}{\numberline {4.1}POST the meta data of the photo}{7}{lstlisting.4.1}
\contentsline {lstlisting}{\numberline {4.2}Response of the HTTP POST with the meta data}{8}{lstlisting.4.2}
\contentsline {lstlisting}{\numberline {4.3}HTTP GET using \lstinline [basicstyle=\relax \fontsize {10.95}{13.6}\selectfont \abovedisplayskip 11\p@ plus3\p@ minus6\p@ \abovedisplayshortskip \z@ plus3\p@ \belowdisplayshortskip 6.5\p@ plus3.5\p@ minus3\p@ \belowdisplayskip \abovedisplayskip \let \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \leftmargin \leftmargini \parsep 4.5\p@ plus2\p@ minus\p@ \topsep 9\p@ plus3\p@ minus5\p@ \itemsep 4.5\p@ plus2\p@ minus\p@ \tt ,aboveskip=10pt,showstringspaces=false]|ESBToken|}{9}{lstlisting.4.3}
\contentsline {lstlisting}{\numberline {4.4}Photo file upload response body}{9}{lstlisting.4.4}
\contentsline {lstlisting}{\numberline {4.5}Response body in case of invalid token}{10}{lstlisting.4.5}
\contentsline {lstlisting}{\numberline {4.6}ImageGetListBySearch sample request}{10}{lstlisting.4.6}
\contentsline {lstlisting}{\numberline {4.7}ImageGetListBySearch sample response body}{10}{lstlisting.4.7}
