//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExecutionState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExecutionState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Activating"/>
 *     &lt;enumeration value="Active"/>
 *     &lt;enumeration value="Suspending"/>
 *     &lt;enumeration value="Suspended"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExecutionState")
@XmlEnum
public enum ExecutionState {

    @XmlEnumValue("Activating")
    ACTIVATING("Activating"),
    @XmlEnumValue("Active")
    ACTIVE("Active"),
    @XmlEnumValue("Suspending")
    SUSPENDING("Suspending"),
    @XmlEnumValue("Suspended")
    SUSPENDED("Suspended");
    private final String value;

    ExecutionState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExecutionState fromValue(String v) {
        for (ExecutionState c: ExecutionState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
