//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HealthState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Operational"/>
 *     &lt;enumeration value="OperationalWithFailures"/>
 *     &lt;enumeration value="Inoperational"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HealthState")
@XmlEnum
public enum HealthState {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("Operational")
    OPERATIONAL("Operational"),
    @XmlEnumValue("OperationalWithFailures")
    OPERATIONAL_WITH_FAILURES("OperationalWithFailures"),
    @XmlEnumValue("Inoperational")
    INOPERATIONAL("Inoperational");
    private final String value;

    HealthState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HealthState fromValue(String v) {
        for (HealthState c: HealthState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
