//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManagementReportFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManagementReportFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncludeExecutionState" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IncludeHealthState" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IncludeMetrics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IncludeFailures" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MetricFilters" type="{http://schemas.tmforum.org/2011/08/ses/smi}MetricFilters" minOccurs="0"/>
 *         &lt;element name="Pagination" type="{http://schemas.tmforum.org/2011/08/ses/smi}Pagination" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManagementReportFilter", propOrder = {
    "includeExecutionState",
    "includeHealthState",
    "includeMetrics",
    "includeFailures",
    "metricFilters",
    "pagination"
})
public class ManagementReportFilter {

    @XmlElement(name = "IncludeExecutionState", defaultValue = "true")
    protected Boolean includeExecutionState;
    @XmlElement(name = "IncludeHealthState", defaultValue = "true")
    protected Boolean includeHealthState;
    @XmlElement(name = "IncludeMetrics", defaultValue = "true")
    protected Boolean includeMetrics;
    @XmlElement(name = "IncludeFailures", defaultValue = "true")
    protected Boolean includeFailures;
    @XmlElement(name = "MetricFilters")
    protected MetricFilters metricFilters;
    @XmlElement(name = "Pagination")
    protected Pagination pagination;

    /**
     * Gets the value of the includeExecutionState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeExecutionState() {
        return includeExecutionState;
    }

    /**
     * Sets the value of the includeExecutionState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeExecutionState(Boolean value) {
        this.includeExecutionState = value;
    }

    /**
     * Gets the value of the includeHealthState property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeHealthState() {
        return includeHealthState;
    }

    /**
     * Sets the value of the includeHealthState property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeHealthState(Boolean value) {
        this.includeHealthState = value;
    }

    /**
     * Gets the value of the includeMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeMetrics() {
        return includeMetrics;
    }

    /**
     * Sets the value of the includeMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeMetrics(Boolean value) {
        this.includeMetrics = value;
    }

    /**
     * Gets the value of the includeFailures property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeFailures() {
        return includeFailures;
    }

    /**
     * Sets the value of the includeFailures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeFailures(Boolean value) {
        this.includeFailures = value;
    }

    /**
     * Gets the value of the metricFilters property.
     * 
     * @return
     *     possible object is
     *     {@link MetricFilters }
     *     
     */
    public MetricFilters getMetricFilters() {
        return metricFilters;
    }

    /**
     * Sets the value of the metricFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetricFilters }
     *     
     */
    public void setMetricFilters(MetricFilters value) {
        this.metricFilters = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

}
