//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tmforum.schemas.smi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tmforum.schemas.smi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XPathFilter }
     * 
     */
    public XPathFilter createXPathFilter() {
        return new XPathFilter();
    }

    /**
     * Create an instance of {@link Metric }
     * 
     */
    public Metric createMetric() {
        return new Metric();
    }

    /**
     * Create an instance of {@link ManagementReportFilter }
     * 
     */
    public ManagementReportFilter createManagementReportFilter() {
        return new ManagementReportFilter();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link Failures }
     * 
     */
    public Failures createFailures() {
        return new Failures();
    }

    /**
     * Create an instance of {@link ServiceConfigurationFilter }
     * 
     */
    public ServiceConfigurationFilter createServiceConfigurationFilter() {
        return new ServiceConfigurationFilter();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Metrics }
     * 
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link Failure }
     * 
     */
    public Failure createFailure() {
        return new Failure();
    }

    /**
     * Create an instance of {@link ManagementReport }
     * 
     */
    public ManagementReport createManagementReport() {
        return new ManagementReport();
    }

    /**
     * Create an instance of {@link MetricFilters }
     * 
     */
    public MetricFilters createMetricFilters() {
        return new MetricFilters();
    }

    /**
     * Create an instance of {@link MetricFilter }
     * 
     */
    public MetricFilter createMetricFilter() {
        return new MetricFilter();
    }

}
