//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.tmforum.org/2011/08/ses/smi", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tmforum.schemas.smi;
