//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceConfigurationFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceConfigurationFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XPathFilter" type="{http://schemas.tmforum.org/2011/08/ses/smi}XPathFilter" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceConfigurationFilter", propOrder = {
    "xPathFilter"
})
public class ServiceConfigurationFilter {

    @XmlElement(name = "XPathFilter")
    protected XPathFilter xPathFilter;

    /**
     * Gets the value of the xPathFilter property.
     * 
     * @return
     *     possible object is
     *     {@link XPathFilter }
     *     
     */
    public XPathFilter getXPathFilter() {
        return xPathFilter;
    }

    /**
     * Sets the value of the xPathFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XPathFilter }
     *     
     */
    public void setXPathFilter(XPathFilter value) {
        this.xPathFilter = value;
    }

}
