//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:19:05 PM BST 
//


package org.tmforum.schemas.smi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for State complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="State">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Health" type="{http://schemas.tmforum.org/2011/08/ses/smi}HealthState" minOccurs="0"/>
 *         &lt;element name="Execution" type="{http://schemas.tmforum.org/2011/08/ses/smi}ExecutionState" minOccurs="0"/>
 *         &lt;element name="Failures" type="{http://schemas.tmforum.org/2011/08/ses/smi}Failures" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "State", propOrder = {
    "health",
    "execution",
    "failures"
})
public class State {

    @XmlElement(name = "Health")
    protected HealthState health;
    @XmlElement(name = "Execution")
    protected ExecutionState execution;
    @XmlElement(name = "Failures")
    protected Failures failures;

    /**
     * Gets the value of the health property.
     * 
     * @return
     *     possible object is
     *     {@link HealthState }
     *     
     */
    public HealthState getHealth() {
        return health;
    }

    /**
     * Sets the value of the health property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthState }
     *     
     */
    public void setHealth(HealthState value) {
        this.health = value;
    }

    /**
     * Gets the value of the execution property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionState }
     *     
     */
    public ExecutionState getExecution() {
        return execution;
    }

    /**
     * Sets the value of the execution property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionState }
     *     
     */
    public void setExecution(ExecutionState value) {
        this.execution = value;
    }

    /**
     * Gets the value of the failures property.
     * 
     * @return
     *     possible object is
     *     {@link Failures }
     *     
     */
    public Failures getFailures() {
        return failures;
    }

    /**
     * Sets the value of the failures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Failures }
     *     
     */
    public void setFailures(Failures value) {
        this.failures = value;
    }

}
